"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pyftpd.py']
APP_NAME = "AwooaPyftpd"
DATA_FILES = []
OPTIONS = {
    'argv_emulation': False,
    'iconfile': 'images/AppIcon.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "ftpd on 2121 port",
        'CFBundleIdentifier': "com.awooa.tools.ftpd",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2020, awooa.com, All Rights Reserved"
    }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
